(module system racket/base
	(require
		racket/contract
	)
	(provide (contract-out
		(apf-fatal (->* (string?) #:rest list? void?))
		(apf-error (->* (string?) #:rest list? void?))
		(apf-warn (->* (string?) #:rest list? void?))
		(apf-info (->* (string?) #:rest list? void?))
		(apf-debug (->* (string?) #:rest list? void?))
	))

	(define (apf-message level pattern . values)
		(let ((logger (current-logger)))
		  (when (log-level? logger level)
		    (log-message logger level 'l2apf (apply format pattern values))
		  )
	  )
	)
	(define (apf-fatal pattern . values)
		(apply apf-message 'fatal pattern values)
	)
	(define (apf-error pattern . values)
		(apply apf-message 'error pattern values)
	)
	(define (apf-warn pattern . values)
		(apply apf-message 'warning pattern values)
	)
	(define (apf-info pattern . values)
		(apply apf-message 'info pattern values)
	)
	(define (apf-debug pattern . values)
		(apply apf-message 'debug pattern values)
	)
)
